'use strict';

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { Scheduler } from '../src/main/scheduler.js';
import { nextCronTime } from '../src/main/cron-parser.js';

// ── Mocks ──

function createMockScheduleRepo() {
  const schedules = new Map();
  const logs = [];
  let idCounter = 0;

  return {
    schedules, logs,
    create(schedule) {
      const id = schedule.id || `sched-${++idCounter}`;
      const record = {
        ...schedule,
        id,
        enabled: schedule.enabled !== false,
        executionCount: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };
      schedules.set(id, record);
      return record;
    },
    getById(id) { return schedules.get(id) || null; },
    update(id, updates) {
      const existing = schedules.get(id);
      if (!existing) return null;
      const updated = { ...existing, ...updates, id, updatedAt: new Date().toISOString() };
      schedules.set(id, updated);
      return updated;
    },
    delete(id) { return schedules.delete(id); },
    list() { return { items: [...schedules.values()], total: schedules.size }; },
    listDue() {
      const now = new Date().toISOString();
      return [...schedules.values()].filter(s => s.enabled && (!s.nextRunAt || s.nextRunAt <= now));
    },
    listAllEnabled() {
      return [...schedules.values()].filter(s => s.enabled);
    },
    toggleEnabled(id, enabled) {
      const s = schedules.get(id);
      if (!s) return null;
      s.enabled = enabled;
      s.updatedAt = new Date().toISOString();
      return s;
    },
    updateNextRun(id, nextRunAt) {
      const s = schedules.get(id);
      if (s) { s.nextRunAt = nextRunAt.toISOString(); s.updatedAt = new Date().toISOString(); }
    },
    incrementExecution(id) {
      const s = schedules.get(id);
      if (s) { s.executionCount++; s.lastRunAt = new Date().toISOString(); s.updatedAt = new Date().toISOString(); }
    },
    addLog(entry) { logs.push({ ...entry, triggeredAt: new Date().toISOString() }); },
    listLogs(scheduleId, limit = 50) { return logs.filter(l => l.scheduleId === scheduleId).slice(0, limit); },
  };
}

function createMockTaskRepo() {
  const tasks = new Map();
  let idCounter = 0;
  return {
    tasks,
    create(task) {
      const id = `task-${++idCounter}`;
      const record = { ...task, id, status: 'pending', createdAt: Date.now(), updatedAt: Date.now() };
      tasks.set(id, record);
      return record;
    },
    getById(id) { return tasks.get(id) || null; },
  };
}

// ── Tests ──

describe('Scheduler', () => {
  let scheduleRepo, taskRepo, scheduler;

  beforeEach(() => {
    scheduleRepo = createMockScheduleRepo();
    taskRepo = createMockTaskRepo();
    scheduler = new Scheduler({ scheduleRepo, taskRepo });
  });

  afterEach(() => {
    scheduler.stop();
  });

  it('creates a scheduler instance', () => {
    expect(scheduler).toBeDefined();
    expect(scheduler._running).toBe(false);
  });

  it('start() and stop() toggle running state', () => {
    scheduler.start();
    expect(scheduler._running).toBe(true);
    scheduler.stop();
    expect(scheduler._running).toBe(false);
  });

  it('_trigger creates a task from template', () => {
    const schedule = scheduleRepo.create({
      name: 'Test Schedule',
      cronExpr: '* * * * *',
      taskTemplate: { title: 'Auto Task', description: 'Generated by scheduler' },
      nextRunAt: new Date().toISOString(),
    });

    scheduler._trigger(schedule);

    expect(taskRepo.tasks.size).toBe(1);
    const task = [...taskRepo.tasks.values()][0];
    expect(task.title).toBe('Auto Task');
    expect(task.description).toBe('Generated by scheduler');
  });

  it('_trigger increments execution count', () => {
    const schedule = scheduleRepo.create({
      name: 'Count Test',
      cronExpr: '* * * * *',
      taskTemplate: { title: 'Task' },
      nextRunAt: new Date().toISOString(),
    });

    scheduler._trigger(schedule);
    const updated = scheduleRepo.getById(schedule.id);
    expect(updated.executionCount).toBe(1);

    scheduler._trigger(updated);
    const updated2 = scheduleRepo.getById(schedule.id);
    expect(updated2.executionCount).toBe(2);
  });

  it('_trigger auto-disables when maxExecutions reached', () => {
    const schedule = scheduleRepo.create({
      name: 'Limited Schedule',
      cronExpr: '* * * * *',
      taskTemplate: { title: 'Task' },
      maxExecutions: 2,
      nextRunAt: new Date().toISOString(),
    });

    scheduler._trigger(schedule);
    scheduler._trigger(scheduleRepo.getById(schedule.id));

    const final = scheduleRepo.getById(schedule.id);
    expect(final.enabled).toBe(false);
    expect(final.executionCount).toBe(2);
  });

  it('_trigger records logs', () => {
    const schedule = scheduleRepo.create({
      name: 'Log Test',
      cronExpr: '* * * * *',
      taskTemplate: { title: 'Task' },
      nextRunAt: new Date().toISOString(),
    });

    scheduler._trigger(schedule);
    expect(scheduleRepo.logs.length).toBe(1);
    expect(scheduleRepo.logs[0].status).toBe('triggered');
    expect(scheduleRepo.logs[0].taskId).toBeTruthy();
  });

  it('_trigger emits schedule:triggered event', () => {
    const schedule = scheduleRepo.create({
      name: 'Event Test',
      cronExpr: '* * * * *',
      taskTemplate: { title: 'Task' },
      nextRunAt: new Date().toISOString(),
    });

    let emitted = null;
    scheduler.on('schedule:triggered', (data) => { emitted = data; });
    scheduler._trigger(schedule);

    expect(emitted).not.toBeNull();
    expect(emitted.scheduleId).toBe(schedule.id);
    expect(emitted.taskId).toBeTruthy();
  });

  it('_trigger handles errors gracefully', () => {
    const schedule = scheduleRepo.create({
      name: 'Error Test',
      cronExpr: '* * * * *',
      taskTemplate: { title: 'Task' },
      nextRunAt: new Date().toISOString(),
    });

    // Make taskRepo.create throw
    const originalCreate = taskRepo.create;
    taskRepo.create = () => { throw new Error('DB down'); };

    scheduler._trigger(schedule);

    // Should log failure
    expect(scheduleRepo.logs.length).toBe(1);
    expect(scheduleRepo.logs[0].status).toBe('failed');
    expect(scheduleRepo.logs[0].error).toBe('DB down');

    // Restore
    taskRepo.create = originalCreate;
  });

  it('recoverOnStartup recalculates next_run_at for enabled schedules', () => {
    // Create a schedule with no nextRunAt
    const schedule = scheduleRepo.create({
      name: 'Recovery Test',
      cronExpr: '0 9 * * *',
      taskTemplate: { title: 'Task' },
    });

    scheduler.recoverOnStartup();

    const updated = scheduleRepo.getById(schedule.id);
    expect(updated.nextRunAt).toBeTruthy();
    const next = new Date(updated.nextRunAt);
    expect(next.getHours()).toBe(9);
    expect(next.getMinutes()).toBe(0);
  });

  it('triggerNow throws for nonexistent schedule', () => {
    expect(() => scheduler.triggerNow('nonexistent')).toThrow('not found');
  });

  it('triggerNow triggers a schedule on demand', () => {
    const schedule = scheduleRepo.create({
      name: 'Manual Trigger',
      cronExpr: '* * * * *',
      taskTemplate: { title: 'Manual Task' },
    });

    scheduler.triggerNow(schedule.id);
    expect(taskRepo.tasks.size).toBe(1);
    expect(scheduleRepo.getById(schedule.id).executionCount).toBe(1);
  });
});
